import hashlib
import hmac
import json
import os
import secrets
import sys
import urllib.parse
from contextlib import asynccontextmanager
from pathlib import Path

from dotenv import load_dotenv
from fastapi import Cookie, Depends, FastAPI, Form, HTTPException, Query, Request
from fastapi.responses import HTMLResponse, RedirectResponse
from fastapi.templating import Jinja2Templates
from tortoise import Tortoise
from tortoise.functions import Count

# Allow importing db.models when running standalone (outside the project root).
sys.path.insert(0, str(Path(__file__).parent.parent))
from db.models import Image  # noqa: E402

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

# load_dotenv is called here so the web app works standalone.
# When launched from main.py it is a no-op (vars already set).
load_dotenv(override=False)

DB_PATH = os.getenv("SQLITE_PATH", "artbot.db")
CONFIG_PATH = Path(os.getenv("CONFIG_PATH", "./configs"))
PAGE_SIZE = 50
CONFIG_PAGE_SIZE = 100
BASE_DIR = Path(__file__).parent

ADMIN_USERNAME: str = os.getenv("ADMIN_USERNAME", "admin")
ADMIN_PASSWORD: str = os.getenv("ADMIN_PASSWORD", "")

_raw_key = os.getenv("WEB_SECRET") or os.getenv("TOKEN", "fallback-key")
SIGNING_KEY: bytes = hashlib.sha256(f"artbot-web:{_raw_key}".encode()).digest()
COOKIE_NAME = "abadmin_session"

# Only files actually loaded by config.py / the bot.
CONFIGS: dict[str, dict] = {
    "char_map": {
        "file": "char_map.json",
        "type": "dict",
        "label": "Character Map",
        "description": "ML tag → character display name. Auto-generated by Danbooru scraper.",
        "auto_generated": True,
    },
    "series_map": {
        "file": "series_map.json",
        "type": "dict",
        "label": "Series Map",
        "description": "ML tag → series/game name used to match forum channels.",
        "auto_generated": False,
    },
    "safety_map": {
        "file": "safety_map.json",
        "type": "dict",
        "label": "Safety Map",
        "description": "Rating tag → safety level suffix used to match forum channel names.",
        "auto_generated": False,
    },
    "webhooks": {
        "file": "webhooks.json",
        "type": "raw",
        "label": "Webhooks",
        "description": "Channel name → list of webhook env var names for cross-posting.",
        "auto_generated": False,
    },
    "target_series": {
        "file": "target_series.json",
        "type": "list",
        "label": "Target Series",
        "description": "Series tags included in auto character extraction from Danbooru.",
        "auto_generated": False,
    },
    "skip_tags": {
        "file": "skip_tags.json",
        "type": "list",
        "label": "Skip Tags",
        "description": "Tags explicitly excluded from auto character extraction.",
        "auto_generated": False,
    },
    "manual_overrides": {
        "file": "manual_overrides.json",
        "type": "dict",
        "label": "Manual Overrides",
        "description": "Manual tag → display name overrides, applied before Danbooru lookup.",
        "auto_generated": False,
    },
}

# ---------------------------------------------------------------------------
# Database lifespan — only initialise Tortoise when running standalone.
# When launched via main.py the bot already owns the connection.
# ---------------------------------------------------------------------------

_tortoise_owned = False


@asynccontextmanager
async def lifespan(_: FastAPI):
    global _tortoise_owned
    try:
        Tortoise.get_connection("default")
    except Exception:
        _tortoise_owned = True
        await Tortoise.init(
            db_url=f"sqlite://{DB_PATH}",
            modules={"models": ["db.models"]},
        )
        conn = Tortoise.get_connection("default")
        await conn.execute_query("PRAGMA foreign_keys = ON;")
        await conn.execute_query("PRAGMA journal_mode = WAL;")
    yield
    if _tortoise_owned:
        await Tortoise.close_connections()


# ---------------------------------------------------------------------------
# App + templates
# ---------------------------------------------------------------------------

app = FastAPI(title="Art Bot Admin", lifespan=lifespan)
templates = Jinja2Templates(directory=BASE_DIR / "templates")


def build_page_url(page: int, platform: str, guild_id: str, search: str) -> str:
    params: dict[str, str] = {"page": str(page)}
    if platform:
        params["platform"] = platform
    if guild_id:
        params["guild_id"] = guild_id
    if search:
        params["search"] = search
    return "/images?" + urllib.parse.urlencode(params)


templates.env.globals["build_page_url"] = build_page_url

# ---------------------------------------------------------------------------
# Auth helpers
# ---------------------------------------------------------------------------


def make_session_token(username: str) -> str:
    return hmac.new(SIGNING_KEY, username.encode(), digestmod=hashlib.sha256).hexdigest()


def is_valid_token(token: str) -> bool:
    return secrets.compare_digest(token, make_session_token(ADMIN_USERNAME))


class NotAuthenticated(Exception):
    pass


@app.exception_handler(NotAuthenticated)
async def not_authenticated_handler(request: Request, _: NotAuthenticated) -> RedirectResponse:
    next_path = urllib.parse.quote(request.url.path, safe="")
    return RedirectResponse(f"/login?next={next_path}", status_code=303)


def require_auth(session: str | None = Cookie(default=None, alias=COOKIE_NAME)) -> None:
    if not ADMIN_PASSWORD or not session or not is_valid_token(session):
        raise NotAuthenticated()


def safe_next(next_url: str) -> str:
    parsed = urllib.parse.urlparse(next_url)
    if parsed.scheme or parsed.netloc:
        return "/"
    return next_url or "/"


# ---------------------------------------------------------------------------
# Config helpers
# ---------------------------------------------------------------------------


def load_config(name: str):
    meta = CONFIGS[name]
    path = CONFIG_PATH / meta["file"]
    if not path.exists():
        return {} if meta["type"] in ("dict", "raw") else []
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


_bot_config = None  # Set by main.py when running combined — allows live reload.


def set_bot_config(config) -> None:
    global _bot_config
    _bot_config = config


def save_config(name: str, data) -> None:
    meta = CONFIGS[name]
    path = CONFIG_PATH / meta["file"]
    tmp = path.with_suffix(".tmp")
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    tmp.replace(path)
    # Reload the bot's in-memory config so changes take effect immediately.
    if _bot_config is not None:
        _bot_config.reload_all()


# ---------------------------------------------------------------------------
# Auth routes
# ---------------------------------------------------------------------------


@app.get("/login", response_class=HTMLResponse)
async def login_page(request: Request, next: str = "/"):
    session = request.cookies.get(COOKIE_NAME)
    if session and ADMIN_PASSWORD and is_valid_token(session):
        return RedirectResponse(safe_next(next), status_code=303)
    return templates.TemplateResponse(
        request, "login.html",
        {"next": next, "error": None, "no_password": not ADMIN_PASSWORD},
    )


@app.post("/login", response_class=HTMLResponse)
async def login_submit(
    request: Request,
    username: str = Form(),
    password: str = Form(),
    next: str = Form(default="/"),
):
    if not ADMIN_PASSWORD:
        return templates.TemplateResponse(
            request, "login.html",
            {"next": next, "error": None, "no_password": True},
            status_code=503,
        )
    valid = secrets.compare_digest(username, ADMIN_USERNAME) and secrets.compare_digest(
        password, ADMIN_PASSWORD
    )
    if not valid:
        return templates.TemplateResponse(
            request, "login.html",
            {"next": next, "error": "Invalid username or password.", "no_password": False},
            status_code=401,
        )
    response = RedirectResponse(safe_next(next), status_code=303)
    response.set_cookie(
        COOKIE_NAME, make_session_token(ADMIN_USERNAME),
        httponly=True, samesite="lax", max_age=60 * 60 * 24 * 7,
    )
    return response


@app.post("/logout")
async def logout():
    response = RedirectResponse("/login", status_code=303)
    response.delete_cookie(COOKIE_NAME)
    return response


# ---------------------------------------------------------------------------
# Image routes (use shared Tortoise ORM / db.models.Image)
# ---------------------------------------------------------------------------


@app.get("/", response_class=HTMLResponse, dependencies=[Depends(require_auth)])
async def root():
    return RedirectResponse("/images")


@app.get("/images", response_class=HTMLResponse, dependencies=[Depends(require_auth)])
async def images_page(
    request: Request,
    page: int = Query(1, ge=1),
    platform: str = Query(""),
    guild_id: str = Query(""),
    search: str = Query(""),
):
    qs = Image.all()
    if platform:
        qs = qs.filter(source_platform=platform)
    if guild_id.strip():
        try:
            qs = qs.filter(guild_id=int(guild_id.strip()))
        except ValueError:
            pass
    if search.strip():
        qs = qs.filter(source_url__icontains=search.strip())

    total = await qs.count()
    offset = (page - 1) * PAGE_SIZE
    rows = await qs.order_by("-posted_at").offset(offset).limit(PAGE_SIZE)

    stats_total = await Image.all().count()

    platform_rows = (
        await Image.all()
        .annotate(count=Count("id"))
        .group_by("source_platform")
        .values("source_platform", "count")
    )
    stats_by_platform = {r["source_platform"]: r["count"] for r in platform_rows}

    guild_ids = await Image.all().distinct().values_list("guild_id", flat=True)
    stats_guilds = len(set(guild_ids))

    platform_list = sorted(
        {r["source_platform"] for r in await Image.all().values("source_platform")}
    )

    total_pages = max(1, (total + PAGE_SIZE - 1) // PAGE_SIZE)

    return templates.TemplateResponse(
        request, "index.html",
        {
            "active_page": "images",
            "db_path": DB_PATH,
            "rows": [
                {
                    "id": r.id,
                    "source_platform": r.source_platform,
                    "source_url": r.source_url,
                    "guild_id": r.guild_id,
                    "thread_id": r.thread_id,
                    "message_id": r.message_id,
                    "posted_at": r.posted_at.strftime("%Y-%m-%d %H:%M:%S") if r.posted_at else "",
                }
                for r in rows
            ],
            "stats": {
                "total": stats_total,
                "by_platform": stats_by_platform,
                "guilds": stats_guilds,
            },
            "platforms": platform_list,
            "total": total,
            "page": page,
            "total_pages": total_pages,
            "filter_platform": platform,
            "filter_guild": guild_id,
            "filter_search": search,
        },
    )


@app.post("/images/{image_id}/delete", dependencies=[Depends(require_auth)])
async def delete_image(image_id: int, request: Request):
    await Image.filter(id=image_id).delete()
    referer = request.headers.get("referer", "/images")
    return RedirectResponse(referer, status_code=303)


# ---------------------------------------------------------------------------
# Config routes
# ---------------------------------------------------------------------------


def _config_ctx(name: str, extra: dict) -> dict:
    return {"active_page": "configs", "db_path": DB_PATH,
            "config_name": name, "config_meta": CONFIGS[name], **extra}


@app.get("/configs", response_class=HTMLResponse, dependencies=[Depends(require_auth)])
async def configs_overview(request: Request):
    items = []
    for name, meta in CONFIGS.items():
        data = load_config(name)
        items.append({
            "name": name, "label": meta["label"], "description": meta["description"],
            "type": meta["type"], "count": len(data),
            "auto_generated": meta.get("auto_generated", False),
        })
    return templates.TemplateResponse(
        request, "configs.html",
        {"active_page": "configs", "db_path": DB_PATH, "items": items},
    )


@app.get("/configs/{name}", response_class=HTMLResponse, dependencies=[Depends(require_auth)])
async def config_view(
    request: Request,
    name: str,
    search: str = Query(""),
    page: int = Query(1, ge=1),
):
    if name not in CONFIGS:
        raise HTTPException(status_code=404, detail="Config not found")

    meta = CONFIGS[name]
    data = load_config(name)
    saved = request.query_params.get("saved") == "1"

    if meta["type"] == "dict":
        entries = list(data.items())
        if search:
            sl = search.lower()
            entries = [(k, v) for k, v in entries if sl in k.lower() or sl in str(v).lower()]
        total = len(entries)
        total_pages = max(1, (total + CONFIG_PAGE_SIZE - 1) // CONFIG_PAGE_SIZE)
        page = min(page, total_pages)
        page_entries = entries[(page - 1) * CONFIG_PAGE_SIZE: page * CONFIG_PAGE_SIZE]
        ctx = _config_ctx(name, {
            "entries": page_entries, "total": total, "total_count": len(data),
            "page": page, "total_pages": total_pages, "search": search, "saved": saved,
        })
    elif meta["type"] == "list":
        items = data
        if search:
            sl = search.lower()
            items = [i for i in items if sl in i.lower()]
        ctx = _config_ctx(name, {
            "items": items, "total": len(data), "search": search, "saved": saved,
        })
    else:
        ctx = _config_ctx(name, {
            "raw_content": json.dumps(data, indent=2, ensure_ascii=False),
            "saved": saved, "error": None,
        })

    return templates.TemplateResponse(request, "config.html", ctx)


@app.post("/configs/{name}/add", dependencies=[Depends(require_auth)])
async def config_add(name: str, key: str = Form(""), value: str = Form(""), item: str = Form("")):
    if name not in CONFIGS:
        raise HTTPException(status_code=404)
    meta = CONFIGS[name]
    data = load_config(name)
    if meta["type"] == "dict" and key.strip():
        data[key.strip()] = value.strip()
        save_config(name, data)
    elif meta["type"] == "list" and item.strip() and item.strip() not in data:
        data.append(item.strip())
        save_config(name, data)
    return RedirectResponse(f"/configs/{name}?saved=1", status_code=303)


@app.post("/configs/{name}/edit", dependencies=[Depends(require_auth)])
async def config_edit_entry(
    request: Request,
    name: str,
    old_key: str = Form(),
    new_key: str = Form(),
    new_value: str = Form(),
):
    if name not in CONFIGS or CONFIGS[name]["type"] != "dict":
        raise HTTPException(status_code=404)
    data = load_config(name)
    if old_key in data:
        del data[old_key]
    if new_key.strip():
        data[new_key.strip()] = new_value.strip()
    save_config(name, data)
    referer = request.headers.get("referer", f"/configs/{name}")
    return RedirectResponse(referer, status_code=303)


@app.post("/configs/{name}/delete", dependencies=[Depends(require_auth)])
async def config_delete_entry(
    request: Request,
    name: str,
    key: str = Form(""),
    item: str = Form(""),
):
    if name not in CONFIGS:
        raise HTTPException(status_code=404)
    meta = CONFIGS[name]
    data = load_config(name)
    if meta["type"] == "dict" and key in data:
        del data[key]
        save_config(name, data)
    elif meta["type"] == "list" and item in data:
        data.remove(item)
        save_config(name, data)
    referer = request.headers.get("referer", f"/configs/{name}")
    return RedirectResponse(referer, status_code=303)


@app.post("/configs/{name}/save-raw", dependencies=[Depends(require_auth)])
async def config_save_raw(request: Request, name: str, content: str = Form()):
    if name not in CONFIGS or CONFIGS[name]["type"] != "raw":
        raise HTTPException(status_code=404)
    try:
        data = json.loads(content)
    except json.JSONDecodeError as exc:
        return templates.TemplateResponse(
            request, "config.html",
            _config_ctx(name, {"raw_content": content, "error": f"Invalid JSON: {exc}", "saved": False}),
            status_code=400,
        )
    save_config(name, data)
    return RedirectResponse(f"/configs/{name}?saved=1", status_code=303)
